### ISSUE TITLE
How to use prop elementID?

### ISSUE THREAD

**Issue by aosante** [ipatate/react-router-scroll-memory#33]
Do you have a working example of how to use prop elementID? I have a three column grid filled with card elements. If the user clicks on one of them, I want to return to the position of that element when the user goes back to the grid. But I'm not sure of what to pass to this prop. The library works everywhere else but here. Please help, ou can see what I want to achieve here: https://swoptop-dev.herokuapp.com/s?s?address=United+States

**Comment by ipatate** [comment]
set id on container scrollable and add this id in props. It's just if you use other container than window

**Comment by Slapbox** [comment]
@ipatate any chance you'd consider supporting accepting `className`s too instead of only IDs? Obviously this would rely on people not using a `className` that's used more than once.

The reason we could use this is that the container that we're looking to scroll is a third-party React-based `contentEditable` that doesn't accept an ID property.

**Comment by ipatate** [comment]
The library supports only one container. Using the class name will assume the use of multiple containers. And to support multiple containers, we have to rewrite the entire library.

**Comment by Slapbox** [comment]
@ipatate, to be clear I'm saying that it would be up to the user to only use that class name once, and to offer it as a fallback. This could be made clear in the documentation I think. Then you just `document.querySelector('.the-class-name')` and use the first. If the user wrongly re-uses that class for multiple elements, instances beyond the first result are simply ignored.

Like I said, turns out we don't need it, but I can see a situation where one might.

**Comment by seleckis** [comment]
Maybe better to use refs instead of id or classNames, as it would be React-way?
